/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityLogRouteImport } from './routes/admin.activity-log'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBillsPaymentsRouteImport } from './routes/admin.bills-payments'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPointsRouteImport } from './routes/admin.points'
import { Route as AdminPosIntegrationsRouteImport } from './routes/admin.pos-integrations'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffAccessRouteImport } from './routes/admin.staff-access'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTablesDevicesRouteImport } from './routes/admin.tables-devices'
import { Route as AdminTiersRouteImport } from './routes/admin.tiers'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerBankRouteImport } from './routes/owner.bank'
import { Route as OwnerIntegrationsRouteImport } from './routes/owner.integrations'
import { Route as OwnerOrdersRouteImport } from './routes/owner.orders'
import { Route as OwnerPaymentsRouteImport } from './routes/owner.payments'
import { Route as OwnerPayoutsRouteImport } from './routes/owner.payouts'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerSupportRouteImport } from './routes/owner.support'
import { Route as OwnerThemeRouteImport } from './routes/owner.theme'
import { Route as AdminAuthScreenRouteImport } from './routes/admin.auth.$screen'
import { Route as OwnerMenusIndexRouteImport } from './routes/owner.menus.index'
import { Route as OwnerMenusMenuIdRouteImport } from './routes/owner.menus.$menuId'
import { Route as AdminMenusStudioIndexRouteImport } from './routes/admin.menu-studio.index'
import { Route as AdminMenusStudioMenuIdRouteImport } from './routes/admin.menu-studio.$menuId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityLogRoute = AdminActivityLogRouteImport.update({
  id: '/admin/activity-log',
  path: '/admin/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillsPaymentsRoute = AdminBillsPaymentsRouteImport.update({
  id: '/admin/bills-payments',
  path: '/admin/bills-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/admin/menus',
  path: '/admin/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPointsRoute = AdminPointsRouteImport.update({
  id: '/admin/points',
  path: '/admin/points',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPosIntegrationsRoute = AdminPosIntegrationsRouteImport.update({
  id: '/admin/pos-integrations',
  path: '/admin/pos-integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/admin/restaurants',
  path: '/admin/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffAccessRoute = AdminStaffAccessRouteImport.update({
  id: '/admin/staff-access',
  path: '/admin/staff-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTablesDevicesRoute = AdminTablesDevicesRouteImport.update({
  id: '/admin/tables-devices',
  path: '/admin/tables-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTiersRoute = AdminTiersRouteImport.update({
  id: '/admin/tiers',
  path: '/admin/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBankRoute = OwnerBankRouteImport.update({
  id: '/owner/bank',
  path: '/owner/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIntegrationsRoute = OwnerIntegrationsRouteImport.update({
  id: '/owner/integrations',
  path: '/owner/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/owner/orders',
  path: '/owner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPaymentsRoute = OwnerPaymentsRouteImport.update({
  id: '/owner/payments',
  path: '/owner/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPayoutsRoute = OwnerPayoutsRouteImport.update({
  id: '/owner/payouts',
  path: '/owner/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSupportRoute = OwnerSupportRouteImport.update({
  id: '/owner/support',
  path: '/owner/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerThemeRoute = OwnerThemeRouteImport.update({
  id: '/owner/theme',
  path: '/owner/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthScreenRoute = AdminAuthScreenRouteImport.update({
  id: '/admin/auth/$screen',
  path: '/admin/auth/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMenusIndexRoute = OwnerMenusIndexRouteImport.update({
  id: '/owner/menus/',
  path: '/owner/menus/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMenusMenuIdRoute = OwnerMenusMenuIdRouteImport.update({
  id: '/owner/menus/$menuId',
  path: '/owner/menus/$menuId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenusStudioIndexRoute = AdminMenusStudioIndexRouteImport.update({
  id: '/admin/menu-studio/',
  path: '/admin/menu-studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenusStudioMenuIdRoute = AdminMenusStudioMenuIdRouteImport.update({
  id: '/admin/menu-studio/$menuId',
  path: '/admin/menu-studio/$menuId',
  getParentRoute: () => rootRouteImport,
} as any)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminActivityLogRoute: AdminActivityLogRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBillsPaymentsRoute: AdminBillsPaymentsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPointsRoute: AdminPointsRoute,
  AdminPosIntegrationsRoute: AdminPosIntegrationsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffAccessRoute: AdminStaffAccessRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTablesDevicesRoute: AdminTablesDevicesRoute,
  AdminTiersRoute: AdminTiersRoute,
  OwnerBankRoute: OwnerBankRoute,
  OwnerIntegrationsRoute: OwnerIntegrationsRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerPaymentsRoute: OwnerPaymentsRoute,
  OwnerPayoutsRoute: OwnerPayoutsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerSupportRoute: OwnerSupportRoute,
  OwnerThemeRoute: OwnerThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  AdminAuthScreenRoute: AdminAuthScreenRoute,
  OwnerMenusMenuIdRoute: OwnerMenusMenuIdRoute,
  OwnerMenusIndexRoute: OwnerMenusIndexRoute,
  AdminMenusStudioIndexRoute: AdminMenusStudioIndexRoute,
  AdminMenusStudioMenuIdRoute: AdminMenusStudioMenuIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
