/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityLogRouteImport } from './routes/admin.activity-log'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBillsPaymentsRouteImport } from './routes/admin.bills-payments'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminMenusRouteImport } from './routes/admin.menus'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPointsRouteImport } from './routes/admin.points'
import { Route as AdminPosIntegrationsRouteImport } from './routes/admin.pos-integrations'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffAccessRouteImport } from './routes/admin.staff-access'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTablesDevicesRouteImport } from './routes/admin.tables-devices'
import { Route as AdminTiersRouteImport } from './routes/admin.tiers'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerBankRouteImport } from './routes/owner.bank'
import { Route as OwnerIntegrationsRouteImport } from './routes/owner.integrations'
import { Route as OwnerOrdersRouteImport } from './routes/owner.orders'
import { Route as OwnerPaymentsRouteImport } from './routes/owner.payments'
import { Route as OwnerPayoutsRouteImport } from './routes/owner.payouts'
import { Route as OwnerSettingsRouteImport } from './routes/owner.settings'
import { Route as OwnerSupportRouteImport } from './routes/owner.support'
import { Route as OwnerThemeRouteImport } from './routes/owner.theme'
import { Route as AdminAuthScreenRouteImport } from './routes/admin.auth.$screen'
import { Route as OwnerMenusIndexRouteImport } from './routes/owner.menus.index'
import { Route as OwnerMenusMenuIdRouteImport } from './routes/owner.menus.$menuId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityLogRoute = AdminActivityLogRouteImport.update({
  id: '/admin/activity-log',
  path: '/admin/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBillsPaymentsRoute = AdminBillsPaymentsRouteImport.update({
  id: '/admin/bills-payments',
  path: '/admin/bills-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenusRoute = AdminMenusRouteImport.update({
  id: '/admin/menus',
  path: '/admin/menus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPointsRoute = AdminPointsRouteImport.update({
  id: '/admin/points',
  path: '/admin/points',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPosIntegrationsRoute = AdminPosIntegrationsRouteImport.update({
  id: '/admin/pos-integrations',
  path: '/admin/pos-integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/admin/restaurants',
  path: '/admin/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffAccessRoute = AdminStaffAccessRouteImport.update({
  id: '/admin/staff-access',
  path: '/admin/staff-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/admin/subscribers',
  path: '/admin/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTablesDevicesRoute = AdminTablesDevicesRouteImport.update({
  id: '/admin/tables-devices',
  path: '/admin/tables-devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTiersRoute = AdminTiersRouteImport.update({
  id: '/admin/tiers',
  path: '/admin/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBankRoute = OwnerBankRouteImport.update({
  id: '/owner/bank',
  path: '/owner/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIntegrationsRoute = OwnerIntegrationsRouteImport.update({
  id: '/owner/integrations',
  path: '/owner/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/owner/orders',
  path: '/owner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPaymentsRoute = OwnerPaymentsRouteImport.update({
  id: '/owner/payments',
  path: '/owner/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPayoutsRoute = OwnerPayoutsRouteImport.update({
  id: '/owner/payouts',
  path: '/owner/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSettingsRoute = OwnerSettingsRouteImport.update({
  id: '/owner/settings',
  path: '/owner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSupportRoute = OwnerSupportRouteImport.update({
  id: '/owner/support',
  path: '/owner/support',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerThemeRoute = OwnerThemeRouteImport.update({
  id: '/owner/theme',
  path: '/owner/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthScreenRoute = AdminAuthScreenRouteImport.update({
  id: '/admin/auth/$screen',
  path: '/admin/auth/$screen',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMenusIndexRoute = OwnerMenusIndexRouteImport.update({
  id: '/owner/menus/',
  path: '/owner/menus/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMenusMenuIdRoute = OwnerMenusMenuIdRouteImport.update({
  id: '/owner/menus/$menuId',
  path: '/owner/menus/$menuId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bills-payments': typeof AdminBillsPaymentsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/points': typeof AdminPointsRoute
  '/admin/pos-integrations': typeof AdminPosIntegrationsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff-access': typeof AdminStaffAccessRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tables-devices': typeof AdminTablesDevicesRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/owner/bank': typeof OwnerBankRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/payouts': typeof OwnerPayoutsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/support': typeof OwnerSupportRoute
  '/owner/theme': typeof OwnerThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/admin/auth/$screen': typeof AdminAuthScreenRoute
  '/owner/menus/$menuId': typeof OwnerMenusMenuIdRoute
  '/owner/menus/': typeof OwnerMenusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bills-payments': typeof AdminBillsPaymentsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/points': typeof AdminPointsRoute
  '/admin/pos-integrations': typeof AdminPosIntegrationsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff-access': typeof AdminStaffAccessRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tables-devices': typeof AdminTablesDevicesRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/owner/bank': typeof OwnerBankRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/payouts': typeof OwnerPayoutsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/support': typeof OwnerSupportRoute
  '/owner/theme': typeof OwnerThemeRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/admin/auth/$screen': typeof AdminAuthScreenRoute
  '/owner/menus/$menuId': typeof OwnerMenusMenuIdRoute
  '/owner/menus': typeof OwnerMenusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bills-payments': typeof AdminBillsPaymentsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/menus': typeof AdminMenusRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/points': typeof AdminPointsRoute
  '/admin/pos-integrations': typeof AdminPosIntegrationsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff-access': typeof AdminStaffAccessRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tables-devices': typeof AdminTablesDevicesRoute
  '/admin/tiers': typeof AdminTiersRoute
  '/owner/bank': typeof OwnerBankRoute
  '/owner/integrations': typeof OwnerIntegrationsRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/owner/payments': typeof OwnerPaymentsRoute
  '/owner/payouts': typeof OwnerPayoutsRoute
  '/owner/settings': typeof OwnerSettingsRoute
  '/owner/support': typeof OwnerSupportRoute
  '/owner/theme': typeof OwnerThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/admin/auth/$screen': typeof AdminAuthScreenRoute
  '/owner/menus/$menuId': typeof OwnerMenusMenuIdRoute
  '/owner/menus/': typeof OwnerMenusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/activity-log'
    | '/admin/analytics'
    | '/admin/bills-payments'
    | '/admin/branding'
    | '/admin/members'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/points'
    | '/admin/pos-integrations'
    | '/admin/restaurants'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/staff-access'
    | '/admin/subscribers'
    | '/admin/support'
    | '/admin/tables-devices'
    | '/admin/tiers'
    | '/owner/bank'
    | '/owner/integrations'
    | '/owner/orders'
    | '/owner/payments'
    | '/owner/payouts'
    | '/owner/settings'
    | '/owner/support'
    | '/owner/theme'
    | '/admin/'
    | '/owner/'
    | '/admin/auth/$screen'
    | '/owner/menus/$menuId'
    | '/owner/menus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/activity-log'
    | '/admin/analytics'
    | '/admin/bills-payments'
    | '/admin/branding'
    | '/admin/members'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/points'
    | '/admin/pos-integrations'
    | '/admin/restaurants'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/staff-access'
    | '/admin/subscribers'
    | '/admin/support'
    | '/admin/tables-devices'
    | '/admin/tiers'
    | '/owner/bank'
    | '/owner/integrations'
    | '/owner/orders'
    | '/owner/payments'
    | '/owner/payouts'
    | '/owner/settings'
    | '/owner/support'
    | '/owner/theme'
    | '/admin'
    | '/owner'
    | '/admin/auth/$screen'
    | '/owner/menus/$menuId'
    | '/owner/menus'
  id:
    | '__root__'
    | '/'
    | '/admin/activity-log'
    | '/admin/analytics'
    | '/admin/bills-payments'
    | '/admin/branding'
    | '/admin/members'
    | '/admin/menus'
    | '/admin/notifications'
    | '/admin/points'
    | '/admin/pos-integrations'
    | '/admin/restaurants'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/staff-access'
    | '/admin/subscribers'
    | '/admin/support'
    | '/admin/tables-devices'
    | '/admin/tiers'
    | '/owner/bank'
    | '/owner/integrations'
    | '/owner/orders'
    | '/owner/payments'
    | '/owner/payouts'
    | '/owner/settings'
    | '/owner/support'
    | '/owner/theme'
    | '/admin/'
    | '/owner/'
    | '/admin/auth/$screen'
    | '/owner/menus/$menuId'
    | '/owner/menus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminActivityLogRoute: typeof AdminActivityLogRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBillsPaymentsRoute: typeof AdminBillsPaymentsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMenusRoute: typeof AdminMenusRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPointsRoute: typeof AdminPointsRoute
  AdminPosIntegrationsRoute: typeof AdminPosIntegrationsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffAccessRoute: typeof AdminStaffAccessRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTablesDevicesRoute: typeof AdminTablesDevicesRoute
  AdminTiersRoute: typeof AdminTiersRoute
  OwnerBankRoute: typeof OwnerBankRoute
  OwnerIntegrationsRoute: typeof OwnerIntegrationsRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  OwnerPaymentsRoute: typeof OwnerPaymentsRoute
  OwnerPayoutsRoute: typeof OwnerPayoutsRoute
  OwnerSettingsRoute: typeof OwnerSettingsRoute
  OwnerSupportRoute: typeof OwnerSupportRoute
  OwnerThemeRoute: typeof OwnerThemeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  AdminAuthScreenRoute: typeof AdminAuthScreenRoute
  OwnerMenusMenuIdRoute: typeof OwnerMenusMenuIdRoute
  OwnerMenusIndexRoute: typeof OwnerMenusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity-log': {
      id: '/admin/activity-log'
      path: '/admin/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AdminActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bills-payments': {
      id: '/admin/bills-payments'
      path: '/admin/bills-payments'
      fullPath: '/admin/bills-payments'
      preLoaderRoute: typeof AdminBillsPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menus': {
      id: '/admin/menus'
      path: '/admin/menus'
      fullPath: '/admin/menus'
      preLoaderRoute: typeof AdminMenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/points': {
      id: '/admin/points'
      path: '/admin/points'
      fullPath: '/admin/points'
      preLoaderRoute: typeof AdminPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pos-integrations': {
      id: '/admin/pos-integrations'
      path: '/admin/pos-integrations'
      fullPath: '/admin/pos-integrations'
      preLoaderRoute: typeof AdminPosIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff-access': {
      id: '/admin/staff-access'
      path: '/admin/staff-access'
      fullPath: '/admin/staff-access'
      preLoaderRoute: typeof AdminStaffAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/admin/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tables-devices': {
      id: '/admin/tables-devices'
      path: '/admin/tables-devices'
      fullPath: '/admin/tables-devices'
      preLoaderRoute: typeof AdminTablesDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tiers': {
      id: '/admin/tiers'
      path: '/admin/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AdminTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bank': {
      id: '/owner/bank'
      path: '/owner/bank'
      fullPath: '/owner/bank'
      preLoaderRoute: typeof OwnerBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/integrations': {
      id: '/owner/integrations'
      path: '/owner/integrations'
      fullPath: '/owner/integrations'
      preLoaderRoute: typeof OwnerIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/orders': {
      id: '/owner/orders'
      path: '/owner/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/payments': {
      id: '/owner/payments'
      path: '/owner/payments'
      fullPath: '/owner/payments'
      preLoaderRoute: typeof OwnerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/payouts': {
      id: '/owner/payouts'
      path: '/owner/payouts'
      fullPath: '/owner/payouts'
      preLoaderRoute: typeof OwnerPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/settings': {
      id: '/owner/settings'
      path: '/owner/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof OwnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/support': {
      id: '/owner/support'
      path: '/owner/support'
      fullPath: '/owner/support'
      preLoaderRoute: typeof OwnerSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/theme': {
      id: '/owner/theme'
      path: '/owner/theme'
      fullPath: '/owner/theme'
      preLoaderRoute: typeof OwnerThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth/$screen': {
      id: '/admin/auth/$screen'
      path: '/admin/auth/$screen'
      fullPath: '/admin/auth/$screen'
      preLoaderRoute: typeof AdminAuthScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/menus/': {
      id: '/owner/menus/'
      path: '/owner/menus'
      fullPath: '/owner/menus/'
      preLoaderRoute: typeof OwnerMenusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/menus/$menuId': {
      id: '/owner/menus/$menuId'
      path: '/owner/menus/$menuId'
      fullPath: '/owner/menus/$menuId'
      preLoaderRoute: typeof OwnerMenusMenuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminActivityLogRoute: AdminActivityLogRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBillsPaymentsRoute: AdminBillsPaymentsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMenusRoute: AdminMenusRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPointsRoute: AdminPointsRoute,
  AdminPosIntegrationsRoute: AdminPosIntegrationsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffAccessRoute: AdminStaffAccessRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTablesDevicesRoute: AdminTablesDevicesRoute,
  AdminTiersRoute: AdminTiersRoute,
  OwnerBankRoute: OwnerBankRoute,
  OwnerIntegrationsRoute: OwnerIntegrationsRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerPaymentsRoute: OwnerPaymentsRoute,
  OwnerPayoutsRoute: OwnerPayoutsRoute,
  OwnerSettingsRoute: OwnerSettingsRoute,
  OwnerSupportRoute: OwnerSupportRoute,
  OwnerThemeRoute: OwnerThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  AdminAuthScreenRoute: AdminAuthScreenRoute,
  OwnerMenusMenuIdRoute: OwnerMenusMenuIdRoute,
  OwnerMenusIndexRoute: OwnerMenusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
